version: '3'

services:
################################
#   Setup react js container
################################
  web:
    build: ./server
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./server:/app

